import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    padding: 16,
    backgroundColor: '#f5f5f5',
  },
  container: {
    flex: 1,
    paddingBottom: 24,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
  },
  progressContainer: {
    marginBottom: 24,
  },
  progressBar: {
    height: 10,
    borderRadius: 5,
    marginBottom: 8,
  },
  progressText: {
    textAlign: 'center',
    color: '#666',
  },
  stepContainer: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  stepTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  stepInstructions: {
    fontSize: 14,
    color: '#666',
    marginBottom: 16,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    marginBottom: 16,
    paddingHorizontal: 12,
    backgroundColor: '#f9f9f9',
  },
  dropdown: {
    marginBottom: 16,
    backgroundColor: '#f9f9f9',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
  },
  button: {
    height: 48,
    justifyContent: 'center',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  halfButton: {
    flex: 0.48,
    height: 48,
    justifyContent: 'center',
  },
  // Profile image styles
  profileImageContainer: {
    alignItems: 'center',
    marginVertical: 16,
  },
  profilePreviewContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  profilePreview: {
    width: 150,
    height: 150,
    borderRadius: 75,
    marginBottom: 8,
  },
  emptyProfileContainer: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: '#ddd',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  emptyProfileText: {
    color: '#999',
  },
  // Document styles
  documentLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  documentPreviewContainer: {
    marginBottom: 4,
  },
  documentPreview: {
    width: '100%',
    height: 200,
    backgroundColor: '#f0f0f0',
    marginBottom: 8,
    borderRadius: 4,
  },
  documentButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 8,
    gap: 8,
  },
  documentButtonRow2: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 8,
  },
  documentButton: {
    flex: 0.45,
  },
  birthCertificateContainer: {
    marginTop: 20,
    padding: 16,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  privacyNote: {
    fontSize: 12,
    color: '#6c757d',
    fontStyle: 'italic',
    marginBottom: 12,
    lineHeight: 16,
    textAlign: 'center' as const,
  },
  tipsText: {
    backgroundColor: '#f9f9f9',
    padding: 15,
    borderRadius: 5,
    marginVertical: 15,
    fontSize: 14,
    lineHeight: 20,
  },
  infoContainer: {
    backgroundColor: '#e7f3fe',
    padding: 15,
    borderRadius: 5,
    marginVertical: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#3498db',
  },
  infoTitle: {
    fontWeight: 'bold',
    marginBottom: 10,
    fontSize: 16,
  },
  infoText: {
    lineHeight: 22,
    marginBottom: 10,
  },
  infoText2: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
    marginBottom: 8,
    marginLeft: 4,
  },
  infoNote: {
    fontStyle: 'italic',
    color: '#666',
  },
  datePickerButton: {
    justifyContent: 'center',
    paddingHorizontal: 12,
    height: 50,
  },
  categoryInfo: {
    marginTop: 10,
    marginBottom: 20,
    paddingHorizontal: 15,
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  paperInput: {
    marginBottom: 15,
    backgroundColor: '#fff',
  },
  paperInputOutline: {
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  paperInputContent: {
    paddingHorizontal: 15,
  },
  uploadedNote: {
    fontSize: 12,
    color: 'green',
    marginVertical: 4,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  divider: {
    height: 1,
    backgroundColor: '#ccc',
    marginVertical: 20,
    opacity: 0.6,
  },
  parentConsentContainer: {
    backgroundColor: '#fff3cd',
    borderWidth: 1,
    borderColor: '#ffeaa7',
    borderRadius: 8,
    padding: 16,
    marginVertical: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  parentConsentTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#e17055',
    marginBottom: 8,
    textAlign: 'center',
  },
  parentConsentText: {
    fontSize: 14,
    color: '#636e72',
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'center',
  },
  loginMethodContainer: {
    marginVertical: 16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: '#f8f9fa',
    borderRadius: 6,
  },
  loginMethodTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2d3436',
    marginBottom: 12,
    textAlign: 'center',
  },
  loginMethodButton: {
    marginVertical: 6,
    height: 44,
    justifyContent: 'center',
  },
  consentButton: {
    height: 48,
    justifyContent: 'center',
    marginTop: 16,
    backgroundColor: '#00b894',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  consentCard: {
    width: '90%',
    alignSelf: 'center',
    borderRadius: 12,
    padding: 16,
    backgroundColor: '#fff',
    elevation: 4,
  },
  consentText: {
    fontSize: 16,
    color: '#333',
    marginBottom: 16,
    textAlign: 'center',
  },
  consentGrantedContainer: {
    backgroundColor: '#e8f5e8',
    borderRadius: 8,
    padding: 16,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: '#4caf50',
  },
  consentGrantedTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2e7d32',
    textAlign: 'center',
    marginBottom: 10,
  },
  consentGrantedText: {
    fontSize: 14,
    color: '#388e3c',
    marginBottom: 12,
    textAlign: 'center',
  },
  parentInfoDisplay: {
    backgroundColor: '#f1f8e9',
    borderRadius: 6,
    padding: 12,
    marginVertical: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#4caf50',
  },
  parentInfoText: {
    fontSize: 14,
    color: '#2e7d32',
    marginBottom: 4,
    lineHeight: 18,
  },
  parentInfoLabel: {
    fontWeight: 'bold',
    color: '#1b5e20',
  },
  proceedText: {
    fontSize: 14,
    color: '#4caf50',
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
});
